window.LEO_CIGAR_DATA = {
  meta: {
    title: "Leo Cigar Library",
    subtitle: "THE CIGAR ARCHIVE · 私人收藏 / 2026",
    verifiedAt: "2026-09-16",
    confirmedVarieties: 47,
    notes: "历史购买量不等于现存余量；当前余量未逐支盘点的款式统一标记为“待盘点”。"
  },
  preferences: {
    flavors: ["奶油","雪松","木质","甜感","蜂蜜感","坚果","咖啡","花香"],
    avoid: ["明显辛辣","明显苦味"],
    preferredSizes: ["Corona","Robusto","短时段小雪茄"],
    profile: "偏淡至中等，喜欢奶油、木质、雪松、甜感；补充偏好雪松更多、甜感更多、蜂蜜感、轻花香。"
  },
  inventorySummary: [
    {label:"确认收藏款式", value:"47 款", note:"旧站 v3 已核对"},
    {label:"Smokingpipes 历史", value:"16 单 / 25 SKU / 69 支", note:"2026-08-25 重新逐单核算"},
    {label:"意大利 Toscano/Toscanello", value:"14 盒", note:"榛子4、烈酒4、红原2、原味2、调甜2"},
    {label:"Drew Estate Sun Blessed", value:"10 支", note:"1盒10支，已纠正此前 CAO Solfyre 误识别"},
    {label:"舅舅赠送估值", value:"10 款", note:"旧站 v3 合计估值约 $595.60"},
    {label:"购买成本快照", value:"约 $456.56", note:"旧站 v3 口径；不含赠送估值"}
  ],
  italian: {
    goodsEUR: 96.80,
    proxyRMB: 100,
    boxes: 14,
    items: [
      {name:"Toscanello Hazelnut Raffinato", qty:4, unit:"盒"},
      {name:"Toscanello Aroma Grappa（烈酒味，暂定）", qty:4, unit:"盒"},
      {name:"Toscanello Rosso（红原，暂定）", qty:2, unit:"盒"},
      {name:"Toscano Originale（大盒，暂定）", qty:2, unit:"盒"},
      {name:"Toscano 自然甜感/调甜（大盒，系列待核）", qty:2, unit:"盒"}
    ]
  },
  rules: [
    "详情页保留购买时间、到货时间、养护时间；线上购买在没有实收日期时默认按购买/发货后约20天估算，但需明确标记“估算”。",
    "商品图优先顺序：Smokingpipes（SP）→ 70Cigars（70站）→ 品牌官网；系列图和待核型号必须单独标注，不能伪装成确认实物。",
    "每款雪茄保留全网综合评价，目标至少3个平台/来源；不能确认的数据标记“待迁移/待核实”，不编造评分。",
    "详情页底部提供相似风味雪茄，显示是否已购买/已入库；相似度按风味标签重合自动计算。",
    "保留可交互统计：产地、品牌、浓郁度、风味、来源/获得方式、尺寸/类型。",
    "购买价统一优先显示含分摊运费后的美元落地均价；赠送品使用市场估值，并明确标“赠送估值”。",
    "历史购买量与当前余量分开；现存余量只有盘点后才能作为“库存”显示。",
    "所有待确认型号、尺寸、图片和包装都必须保留“暂定/待确认”标签。"
  ],
  timeline: [
    {date:"2026-08-01", title:"第三单实购", detail:"Fireball Corona ×1；Brick House Double Connecticut Robusto ×1。"},
    {date:"2026-08-25", title:"SP 总账校正", detail:"Smokingpipes 累计16单、25个SKU、69支。"},
    {date:"2026-08-25", title:"意大利代购最终清单", detail:"Toscanello/Toscano 共14盒；货款 €96.80 + 代购费 ¥100。"},
    {date:"2026-09-06", title:"产品识别更正", detail:"原“CAO Solfyre”记录更正为 Drew Estate Isla del Sol Sun Blessed 10 Pack ×1盒（10支）。"},
    {date:"2026-09-08", title:"SP 到货", detail:"AF Exquisitos Maduro、AF Brevas Royal Maduro、Curivari BV F50 CT、Rojas Breakfast Tacos CT、Tatuaje Series P Honduras Short Robusto ×3。"},
    {date:"2026-09-09", title:"SP 两单确认", detail:"两单均记录为 2026-08-24 发货；含 AF Brevas Royale Natural、Baccarat Luchadores/Toro、AF Exquisitos Maduro、RP The Edge CT Robusto、Punch Clasico Maduro London Club、Tatuaje Reserva Petite Cazadores、Tatuaje Series P Honduras Short Robusto、Curivari BV F50 CT、Rojas Breakfast Tacos CT。"},
    {date:"2026-09-12", title:"70Cigars 包裹到货", detail:"旧站已纳入 White Heather、Hambones、Dominican Cream 等5个SKU；数量按订单/实物继续盘点。"},
    {date:"2026-09-12", title:"舅舅赠送新增", detail:"旧站 v3 已并入赠送系列并以市场估值显示；BHK 56 按用户确认“真品”记录。"},
    {date:"2026-09-16", title:"旧站 v3 核对", detail:"47款确认收藏；商品图优先SP/70；待核型号独立标注。"}
  ],
  cigars: [
    {id:1,brand:"Macanudo",name:"Court Café",origin:"多米尼加",flavors:["奶油","坚果","木质","甜感"],strength:"轻柔",price:"$5.86 / 支",stock:"待盘点"},
    {id:2,brand:"Foundation",name:"Charter Oak Connecticut Petite Corona",origin:"尼加拉瓜",flavors:["奶油","木质","香料"],strength:"中等",price:"$7.98 / 支",stock:"待盘点"},
    {id:3,brand:"Perdomo",name:"10th Anniversary Champagne Robusto",origin:"尼加拉瓜",flavors:["奶油","雪松","甜感","木质"],strength:"轻中等",price:"$11.77 / 支",stock:"待盘点"},
    {id:4,brand:"Arturo Fuente",name:"Brevas Royal Maduro",origin:"多米尼加",flavors:["木质","香料","可可","咖啡"],strength:"中等",price:"$4.55 / 支",stock:"待盘点"},
    {id:5,brand:"Fireball",name:"Corona",origin:"多米尼加",flavors:["香料","甜感","木质"],strength:"中等",price:"$6.64 / 支",stock:"待盘点",purchaseDate:"2026-08-01"},
    {id:6,brand:"Brick House",name:"Double Connecticut Robusto",origin:"尼加拉瓜",flavors:["雪松","奶油","甜感","香料"],strength:"轻中等",price:"$10.00 / 支",stock:"待盘点",purchaseDate:"2026-08-01"},
    {id:7,brand:"Zino",name:"Nicaragua Mini Cigarillos",origin:"多米尼加",flavors:["香料","木质","甜感"],strength:"中等",price:"$0.75 / 支",stock:"待盘点"},
    {id:8,brand:"Punch",name:"Elites EMS",origin:"洪都拉斯",flavors:["木质","坚果","香料","咖啡"],strength:"中浓郁",price:"$5.86 / 支",stock:"待盘点"},
    {id:9,brand:"Gran Habano",name:"Connecticut #1 Churchill",origin:"洪都拉斯",flavors:["奶油","坚果","雪松","甜感"],strength:"轻中等",price:"$10.54 / 支",stock:"待盘点",note:"旧站：系列图；订单确认 Churchill 规格"},
    {id:10,brand:"Oliva",name:"Connecticut Reserve Robusto",origin:"尼加拉瓜",flavors:["奶油","雪松","可可","甜感"],strength:"轻中等",price:"$9.20 / 支",stock:"待盘点"},
    {id:11,brand:"El Rey del Mundo",name:"Shade Grown Churchill",origin:"洪都拉斯",flavors:["坚果","木质","香料","奶油"],strength:"轻中等",price:"$7.83 / 支",stock:"待盘点"},
    {id:12,brand:"Arturo Fuente",name:"Exquisitos Maduro",origin:"多米尼加",flavors:["咖啡","可可","木质","甜感"],strength:"中等",price:"$4.18 / 支",stock:"待盘点"},
    {id:13,brand:"Baccarat",name:"Toro",origin:"洪都拉斯",flavors:["甜感","奶油","雪松","可可"],strength:"轻柔",price:"$6.58 / 支",stock:"待盘点"},
    {id:14,brand:"Perdomo",name:"20th Anniversary Connecticut Epicure E656",origin:"尼加拉瓜",flavors:["奶油","雪松","甜感","香料"],strength:"轻中等",price:"$12.89 / 支",stock:"待盘点"},
    {id:15,brand:"United Cigars",name:"Maduro Pencils",origin:"多米尼加",flavors:["咖啡","可可","木质","香料"],strength:"中等",price:"$4.13 / 支",stock:"待盘点"},
    {id:16,brand:"Arturo Fuente",name:"Brevas Royale Natural",origin:"多米尼加",flavors:["木质","香料","坚果"],strength:"中等",price:"$4.53 / 支",stock:"待盘点"},
    {id:17,brand:"Drew Estate",name:"Isla del Sol Sun Blessed · Breve",origin:"尼加拉瓜",flavors:["待核实"],strength:"待核实",price:"$1.93 / 支",stock:"待盘点",knownQty:"10支 / 1盒",note:"2026-09-06 更正：不是 CAO Solfyre"},
    {id:18,brand:"Tatuaje",name:"Series P Honduras Short Robusto",origin:"洪都拉斯",flavors:["待核实"],strength:"待核实",price:"$4.83 / 支",stock:"待盘点",knownQty:"至少3支记录",note:"2026-09-08 到货记录含×3"},
    {id:19,brand:"Punch",name:"Clasico Maduro London Club",origin:"洪都拉斯",flavors:["咖啡","木质","甜感","香料"],strength:"中浓郁",price:"$5.22 / 支",stock:"待盘点"},
    {id:20,brand:"Tatuaje",name:"Reserva Petite Cazadores",origin:"尼加拉瓜",flavors:["咖啡","可可","香料","木质"],strength:"中浓郁",price:"$5.37 / 支",stock:"待盘点"},
    {id:21,brand:"Curivari",name:"Buenaventura Favoritos 50 Connecticut",origin:"尼加拉瓜",flavors:["待核实"],strength:"中浓郁",price:"$6.02 / 支",stock:"待盘点"},
    {id:22,brand:"Baccarat",name:"Luchadores",origin:"洪都拉斯",flavors:["甜感","奶油","雪松","坚果"],strength:"轻柔",price:"$6.31 / 支",stock:"待盘点"},
    {id:23,brand:"Montesino",name:"Napoleon Grande Natural",origin:"多米尼加",flavors:["奶油","雪松","木质","坚果"],strength:"轻柔",price:"$5.74 / 支",stock:"待盘点",note:"70站 Natural 系列图；订单规格 7½×46"},
    {id:24,brand:"Alec Bradley",name:"Project 40 Toro · 06.52",origin:"尼加拉瓜",flavors:["坚果","木质","咖啡","甜感"],strength:"中等",price:"$7.27 / 支",stock:"待盘点"},
    {id:25,brand:"Rojas",name:"Breakfast Tacos Connecticut",origin:"尼加拉瓜",flavors:["奶油","坚果","咖啡","香料"],strength:"中等",price:"$7.07 / 支",stock:"待盘点"},
    {id:26,brand:"Joya de Nicaragua",name:"Joya Black Cigarillos · 10支装",origin:"尼加拉瓜",flavors:["可可","咖啡","木质","香料"],strength:"中浓郁",price:"$1.85 / 支",stock:"待盘点",knownQty:"10支装订单记录",purchaseDate:"2026-09-01",shipDate:"2026-09-02",note:"订单 No. 3934946；订单总额 $18.47"},
    {id:27,brand:"Joya de Nicaragua",name:"Joya Red Cigarillos · 10支装",origin:"尼加拉瓜",flavors:["雪松","坚果","香料","甜感"],strength:"中等",price:"$1.85 / 支",stock:"待盘点"},
    {id:28,brand:"White Heather",name:"Torpedo",origin:"尼加拉瓜",flavors:["奶油"],strength:"浓郁",price:"$4.31 / 支",stock:"待盘点",arrivalDate:"2026-09-12",note:"70Cigars 包裹"},
    {id:29,brand:"Hambones",name:"Habano Torpedo",origin:"洪都拉斯",flavors:["木质","香料","甜感"],strength:"中等",price:"$3.82 / 支",stock:"待盘点",arrivalDate:"2026-09-12",note:"70Cigars 包裹"},
    {id:30,brand:"Hambones",name:"Connecticut Toro",origin:"洪都拉斯",flavors:["奶油","雪松","坚果","甜感"],strength:"轻柔",price:"$3.82 / 支",stock:"待盘点",arrivalDate:"2026-09-12",note:"70Cigars 包裹"},
    {id:31,brand:"Dominican Cream",name:"Churchill",origin:"多米尼加",flavors:["奶油","雪松","甜感","香料"],strength:"轻柔",price:"$4.38 / 支",stock:"待盘点",arrivalDate:"2026-09-12",note:"70Cigars 包裹"},
    {id:32,brand:"Dominican Cream",name:"Robusto",origin:"多米尼加",flavors:["奶油","甜感","花香"],strength:"轻柔",price:"$4.08 / 支",stock:"待盘点",arrivalDate:"2026-09-12",note:"70Cigars 包裹"},
    {id:33,brand:"Plasencia",name:"Reserva Original Robusto",origin:"尼加拉瓜",flavors:["奶油","雪松","甜感","坚果"],strength:"中等",price:"赠送估值 $10.99 / 支",stock:"待盘点",source:"赠送"},
    {id:34,brand:"Rocky Patel",name:"Vintage 1990",origin:"洪都拉斯",flavors:["木质"],strength:"中等",price:"赠送估值 $12.00 / 支",stock:"待盘点",source:"赠送",note:"具体尺寸待核对"},
    {id:35,brand:"Gran Habano",name:"Corojo No.5",origin:"洪都拉斯",flavors:["木质","香料","咖啡","甜感"],strength:"浓郁",price:"赠送估值 $8.50 / 支",stock:"待盘点",source:"赠送",note:"尺寸待确认"},
    {id:36,brand:"Sancho Panza",name:"Double Maduro",origin:"洪都拉斯",flavors:["咖啡","可可","香料","甜感"],strength:"中浓郁",price:"赠送估值 $7.49 / 支",stock:"待盘点",source:"赠送",note:"尺寸待确认"},
    {id:37,brand:"José L. Piedra",name:"Cazadores",origin:"古巴",flavors:["木质","咖啡","甜感","香料"],strength:"中等",price:"赠送估值 $5.70 / 支",stock:"待盘点",source:"赠送"},
    {id:38,brand:"Perdomo",name:"Habano Bourbon Barrel-Aged（疑似）",origin:"尼加拉瓜",flavors:["咖啡","可可","甜感","香料"],strength:"中浓郁",price:"赠送估值 $10.42 / 支",stock:"待盘点",source:"赠送",note:"版本与尺寸待实物确认"},
    {id:39,brand:"E.P. Carrillo",name:"New Wave Connecticut（尺寸待确认）",origin:"多米尼加",flavors:["奶油","雪松","坚果","木质"],strength:"轻中等",price:"赠送估值 $8.00 / 支",stock:"待盘点",source:"赠送"},
    {id:40,brand:"Cohiba",name:"Behike BHK 56",origin:"古巴",flavors:["可可","咖啡","木质","香料"],strength:"中浓郁",price:"赠送估值 $500.00 / 支",stock:"待盘点",source:"赠送",note:"按用户确认记录为真品"},
    {id:41,brand:"H. Upmann",name:"Coronas Major A/T（暂定）",origin:"古巴",flavors:["雪松","坚果","奶油","木质"],strength:"轻中等",price:"赠送估值 $20.00 / 支",stock:"待盘点",source:"赠送",note:"按实物外观暂定；铝管参考"},
    {id:42,brand:"Alec Bradley",name:"Prensado（尺寸待确认）",origin:"洪都拉斯",flavors:["咖啡","可可","木质","香料"],strength:"中浓郁",price:"赠送估值 $12.50 / 支",stock:"待盘点",source:"赠送"},
    {id:43,brand:"Toscanello",name:"Hazelnut Raffinato · 小盒",origin:"意大利",flavors:["坚果","甜感","咖啡","木质"],strength:"轻中等",price:"$9.04 / 盒",stock:"4盒历史购买",knownQty:"4盒",note:"意大利包装待核"},
    {id:44,brand:"Toscanello",name:"Aroma Grappa · 小盒（暂定）",origin:"意大利",flavors:["甜感","木质","香料"],strength:"中等",price:"$9.04 / 盒",stock:"4盒历史购买",knownQty:"4盒",note:"最可能对应“烈酒味”，仍需包装确认"},
    {id:45,brand:"Toscanello",name:"Rosso · 小盒（暂定）",origin:"意大利",flavors:["咖啡","甜感","木质"],strength:"中等",price:"$9.05 / 盒",stock:"2盒历史购买",knownQty:"2盒",note:"“红原”仍需实物确认"},
    {id:46,brand:"Toscano",name:"Originale · 大盒（暂定）",origin:"意大利",flavors:["木质","咖啡","香料"],strength:"浓郁",price:"$9.05 / 盒",stock:"2盒历史购买",knownQty:"2盒",note:"具体包装待核"},
    {id:47,brand:"Toscano",name:"自然甜感 · 大盒（系列待核）",origin:"意大利",flavors:["甜感","木质","香料","咖啡"],strength:"中等",price:"$9.05 / 盒",stock:"2盒历史购买",knownQty:"2盒",note:"旧站使用 Garibaldi 甜润风格参考图，不代表确认型号"}
  ]
};